### ISSUE TITLE
Unable to retrieve resource information from GUTS UI

### ISSUE THREAD

**Issue by BharatKumarK** [aptira/guts-dashboard#1]
I have deployed Guts on a fresh Ubuntu 14.04 machine using devstack.
I can see "Guts" in the left side panel. But internal tabs are not working. Getting below errors:
> Error: Unable to retrieve vms list
> Error: Unable to retrieve VM migrations list
> Error: Unable to retrieve vms list

**Comment by Vaidyanath** [comment]
even I am facing similar issue

**Comment by rajalokan** [comment]
Hi Vaidyanath, I can help you in this. This is working. Can you please paste your log here.

**Comment by rajalokan** [comment]
This is resolved. With latest `guts`, this issue shouldn't occur. Closing this for now.

**Comment by Vaidyanath** [comment]
You say that the keystone version is taken care of?? we dont have to rely on V2 will this work on V3?

**Comment by rajalokan** [comment]
Yes Vaidyanath. On merging https://github.com/aptira/guts-dashboard/pull/5, I can verify both V2 & V3 versions of keystone works. Reopen this if you face this issue.
